AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - bin/**
    - config/**/*
    - spec/**/*
    - spec/dummy/config/initializers/secret_token.rb
    - lib/mail_chimp_batch_update.rb
Documentation:
  Enabled: false
LineLength:
  Enabled: true
  Max: 160
AbcSize:
  Enabled: false
