development:
  clients:
    default:
      database: ch420_development
      # database: heroku_t242kdp0
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: ch420_test
      hosts:
        - localhost:27017
        
production:
  clients:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
